/**
 * Desk & Clicker Domain Types
 * Defines states for Phase 1 (Airport Rubber Stamp) and Phase 2+ (Oval Office Golden Sharpie).
 */

export type GamePhase = 1 | 2 | 3 | 4;

export interface DeskState {
  /** Current evolutionary phase (1: Customs, 2: Oval, 3: Fortress, 4: Ontological) */
  phase: GamePhase;

  /** BagHolder Pro unlocks on the first stamp slam (see [The Ten-Minute Wall] in deskSlice). */
  hasMarketAccess: boolean;

  /**
   * Index into TUTORIAL_CHAIN for the step currently being shown.
   * Equals TUTORIAL_CHAIN.length once onboarding is complete.
   */
  tutorialStepIndex: number;

  /** Regulatory radar unlocks after the first YAP is launched */
  hasRadarAccess: boolean;

  /** Prediction markets unlock after settling a YAP-targeted put */
  hasPolyGriftAccess: boolean;

  /** Lobbying upgrades unlock after the first agency liquidation */
  hasCronyUnlocksAccess: boolean;

  /** Tariff controls unlock after buying a crony upgrade */
  hasTariffAccess: boolean;

  /** Prestige unlocks after the player changes a bilateral tariff */
  hasPrestigeAccess: boolean;

  /** Total manual clicks executed across all sessions */
  totalClicks: number;

  /** Current ink level (0 to 100). When 0, enters "Desperation Dry Nib" state */
  inkLevel: number;

  /** Maximum ink capacity */
  maxInk: number;

  /** Number of times ink has been manually refilled (determines refill cost) */
  inkRefillCount: number;

  /** Tantrum meter (0 to 100). Fills on manual taps; triggers CAPS LOCK FRENZY at 100 */
  tantrumMeter: number;

  /** Whether the Dealmaker is currently in CAPS LOCK FRENZY mode */
  isCapsFrenzy: boolean;

  /** Remaining seconds in active CAPS LOCK FRENZY */
  capsFrenzySecondsRemaining: number;

  /** Total frenzy triggers across playthrough */
  totalFrenziesTriggered: number;

  /**
   * INVARIANT: [The Cooling-Off Protocol]
   * Seconds remaining before the tantrum meter may fill again after a FRENZY ends.
   * Prevents the frenzy infinite-loop where the meter is already at 100% the
   * instant the timer expires. A value > 0 blocks new frenzy triggers.
   */
  frenzyCooldownSecondsRemaining: number;

  /** Number of consecutive dry clicks executed without refilling (caps at 30 before jamming) */
  dryClicksCount: number;

  /** Debounce timestamp for rate-limiting manual clicks */
  lastClickTimestamp: number;

  /** Cooldown timestamp for Subpoena Shredder desk prop */
  lastShredTimestamp: number;

  /** Cooldown timestamp for classified secrets sale */
  lastSecretSaleTimestamp: number;

  /** Cooldown timestamp for the emergency money printer */
  lastPrinterTimestamp: number;

  /** Calculated passive revenue generated by foreign export tariffs ($/sec) */
  tariffRevenuePerSecond: number;

  /**
   * INVARIANT: [The Crisis Call]
   * A live 3:00 AM crisis awaiting a decision on the Red Phone, or null when the
   * phone is quiet. Drives the Crisis Call dial — see constants/crisis.ts.
   */
  activeCrisis: {
    id: string;
    /** Seconds the crisis has been ringing. Drives the escalation tier. */
    elapsedSeconds: number;
  } | null;

  /** Seconds until the next crisis spawns. Only counts down when the phone is quiet. */
  crisisCooldownSeconds: number;

  /** Lifetime crises answered via SWEAR IN. */
  totalCrisesAnswered: number;

  /** Lifetime crises that expired unanswered (suppressed). */
  totalCrisesSuppressed: number;

  /** Most recent Crisis Call outcome, rendered as a transient desk notice. */
  lastCrisisOutcome: string | undefined;
}
